### PR TITLE
install tar package

### PR DESCRIPTION
**Pull request by mddamato**
### Proposed changes
Install tar package if needed before running tar command

### CODE REVIEW

**Comment by dgvigil** [comment]
@tuckcodes Can you pull `main` into this branch to catch up and then push again to see if it passes the tests?

**Comment by tuckcodes** [comment]
Had issues with subscribing to the RHEL8 AMI. Will look deeper into it tomorrow, fix it, and then test this on RHEL8 minimum (no tar).

**Comment by tuckcodes** [comment]
The RHEL8 min AMI had Tar installed, but did a yum remove and seemed to do a clean uninstall of tar. I then tested the script against two agents and two servers with tar uninstalled. Each deploy installed tar as expected, and ran through the ansible script successfully.

**Review by tuckcodes — COMMENTED** [review]
Local testing went through, and everything looks good. The merge should go through a pipeline now as the final test.

**Pull request merged**
