### PR TITLE
working for multiple nodes

### PR DESCRIPTION
**Pull request by brooksphilip**
now works with multiple nodes

### CODE REVIEW

**Comment by dgvigil** [comment]
I understand the restructuring of the directories to allow for immediate `ansible-playbook` use, but I worry that if someone wants to use this playbook in conjunction with other playbooks it may add unneeded confusion.

**Comment by brooksphilip** [comment]
If they want to use it with other playbooks they would just add the role which is why I turned it into a role

**Review by capta1nk1rk — CHANGES_REQUESTED** [review]
@brooksphilip Remove your hosts file from this PR.  Has private IPs associated with your env.

**Comment by brooksphilip** [comment]
IPs removed and changed to 0.0.0.0 also updated vars/main.yml with a node and removed an IP

**Comment by dgvigil** [comment]
Thanks for your contribution @brooksphilip . Before I can merge in your PR, I have to ask that the original directory structure be returned.  I understand how you are setting up the structure, but before this role can be submitted to Ansible Galaxy it must be in the standard format (https://galaxy.ansible.com/docs/contributing/creating_role.html#roles). Please correct this so that we can merge in your changes.

**Pull request closed without merging**
