### PR TITLE
Begin idempotency

### LINKED ISSUE #46: Idempotency
An operation is idempotent if the result of performing it once is exactly the same as the result of performing it repeatedly without any intervening actions

One should be able to run this playbook repeatedly and if no variables or inventory changes then everything should be left as is. There should not be concern about "did I run the playbook with this host/variable yet?" because if nothing has changed then the ansible-playbook run should not change anything.

### PR DESCRIPTION
**Pull request by dgvigil**
## What type of PR is this?

_(REQUIRED)_

- [ ] bug
- [ ] cleanup
- [ ] documentation
- [X ] feature

## What this PR does / why we need it:
You should be able to run this playbook repeatedly without fear of changes to your cluster if no changes were made in variables/configs.  This also allows for adding hosts.

## Which issue(s) this PR fixes:

Fixes #46 

## Testing
The CI tests have changed to verify this change.  The tests run the playbook multiple times to make sure that no changes are made. The tests also adds hosts after the initial run and after the idempotency run.  The ansible and python tests are run a second time after the new hosts are added.

### CODE REVIEW

**Comment by tuckcodes** [comment]
After testing there appears to only be one change logged, which is a restart of the server node; however, the node itself is not changed in any way from what I can tell. 

Checked with Dave over slack and he confirmed that this is something we can't get around, so it will always report one change even though we technically haven't 'changed' anything.

image

**Comment by jmkelm08** [comment]
These changes seem to be causing a breakage for me. I am running on a RedHat system.

```
TASK [rke2_common : Check if rke2-agent is previously installed] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "rke2-agent is already installed. Skipping installation steps."
}

TASK [rke2_common : Set fact if rke2-agent was previously installed] *********************************************************************************************************************
ok: [localhost]

TASK [rke2_common : TARBALL | Make temp dir] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '((ansible_facts['os_family'] != 'RedHat' and\nansible_facts['os_family'] != 'Rocky') or\nrke2_binary_tarball_check.stat.exists == true)\nand not installed' failed. The error was: error while evaluating conditional (((ansible_facts['os_family'] != 'RedHat' and\nansible_facts['os_family'] != 'Rocky') or\nrke2_binary_tarball_check.stat.exists == true)\nand not installed): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/user/git/rke2-ansible/roles/rke2_common/tasks/tarball_install.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: TARBALL | Make temp dir\n  ^ here\n"}
```

I suspect the problem is related to `rke2_binary_tarball_check` no longer getting set in `rke2_common/tasks/main.yml` due to the addition of the when clause on line 22. The subsequent tasks (lines 31 and 45) will attempt to use `rke2_binary_tarball_check` if the OS family is RedHat or Rocky.

**Comment by dgvigil** [comment]
Thank you for reaching out @jmkelm08 . We will investigate.

**Comment by dgvigil** [comment]
@jmkelm08 Can you attempt to run the playbook again after removing line 22 from roles/rke2_common/tasks/main.yml ?
Just the when statement: `when: not installed`
Does it run as expected after removing it?

**Comment by jmkelm08** [comment]
@dgvigil it does seem to run correctly without the `when` clause on line 22

**Pull request merged**
