### PR TITLE
Feat: Add tls-san to rke2_config

### PR DESCRIPTION
**Pull request by Falltrades**
## What type of PR is this?

_(REQUIRED)_

- [ ] bug
- [ ] cleanup
- [ ] documentation
- [x] feature

## What this PR does / why we need it:

_(REQUIRED)_

When trying to reach kube-api server using a kubeconfig with some DNS somednsexample.co, the following error is showing :
```
tls: failed to verify certificate: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not for somednsexample.com
```
A solution would be to add the following in /etc/rancher/rke2/config.yaml:
```
tls-san:
  - somednsexample.com
```
https://docs.rke2.io/reference/server_config#listener

Right now, it is not supported in the Ansible role.

## Which issue(s) this PR fixes:

_(REQUIRED)_

No issue.

## Testing

Tests cases:
- deploying new cluster,
- updating existing cluster.

## Release Notes

_(REQUIRED)_

```release-note
Feat: Add tls-san to rke2_config
```

### CODE REVIEW

**Comment by GoldennDragonn** [comment]
This can be achieved by adding the needed tls-san to the rke2_config, either in rke2-servers.yaml or in hosts.yml and it will be popular to config.yaml.

**Comment by Falltrades** [comment]
> This can be achieved by adding the needed tls-san to the rke2_config, either in rke2-servers.yaml or in hosts.yml and it will be popular to config.yaml.

Yes, it will be achieved as you describe with the two tasks in the PR (I just tested without them just to make sure I didn't miss anything and config.yaml is not getting populated with `tls-san` currently).

**Comment by GoldennDragonn** [comment]
I've just tested without the tasks in the PR and it was populated correctly... Sharing my configuration. However take in consideration that I've commented the rke2_config: {} line in rke2-servers and rke2-agents, because otherwise the vars from hosts.yml were not respected:

```
---
all:
  vars:
    install_rke2_version: v1.27.13+rke2r1
    # # In air-gapped envs, it might be convenient to download the tar files from custom URLs
    # rke2_tarball_url: https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2.linux-amd64.tar.gz
    # rke2_image_tar_urls:
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-canal.linux-amd64.tar.zst
    # - https://github.com/rancher/rke2/releases/download/v1.26.15%2Brke2r1/rke2-images-core.linux-amd64.tar.zst

rke2_cluster:
  children:
    rke2_servers:
      vars:
        # # Set generic rke2_config at the group level.
        # # Every host in this group will inherit these rke2 configurations
        # # See https://docs.rke2.io/reference/server_config for more options
        # # These options can also be set in the group_vars folder
        rke2_config:
          node-label:
            - masters=true
          profile: cis-1.23
          cni: 
            - calico
          disable: 
            - rke2-canal
            # - rke2-ingress-nginx
          tls-san:
            - "192.168.56.101"
            - "192.168.56.102"
            - "192.168.56.103"
            - "master.somedomain.com"
          # kube-controller-manager-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-scheduler-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # kube-apiserver-arg:
          # - "tls-min-version=VersionTLS12"
          # - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
          # - "enable-admission-plugins=ValidatingAdmissionWebhook,NodeRestriction,PodSecurityPolicy"
          # - "request-timeout=300s"
          # # Enable only when auditing is enabled, blocks API when audit fails
          # #- "audit-log-mode=blocking-strict"
          #
          # kubelet-arg:
          # - "feature-gates=DynamicKubeletConfig=false"
          # - "protect-kernel-defaults=true"
          # - "streaming-connection-idle-timeout=5m"
          #
          # etcd-extra-env:
          # - "ETCD_AUTO_TLS=false"
          # - "ETCD_PEER_AUTO_TLS=false"
          #
          admission-control-config-file: "/etc/rancher/rke2/pod-security-admission-config.yaml"

          write-kubeconfig-mode: "0644"
        # # See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
        # # Add a policy configuration file by specifying the file path on the control host
        audit_policy_config_file_path: "{{ playbook_dir }}/extraconfigs/audit-policy.yaml"
        # # See https://docs.rke2.io/install/containerd_registry_configuration/
        # # Add a registry configuration file by specifying the file path on the control host
        registry_config_file_path: "{{ playbook_dir }}/extraconfigs/registries.yaml"
        # # See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
        # # Add manifest files by specifying the directory path on the control host
        manifest_config_file_path: "{{ playbook_dir }}/extraconfigs/manifest/"
        # # See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
        # # Add manifest files by specifying the directory path on the control host
        cluster_manifest_config_file_path: "{{ playbook_dir }}/extraconfigs/cluster_manifest/"
        # See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces
        # Available in RKE2 1.25+
        # Add a pod security admission config file by specifying the file path on the control host
        # Requires config.yaml to include `- admission-control-config-file=/etc/rancher/rke2/pod-security-admission-config.yaml` in order for this to be honored
        pod_security_admission_config_file_path: "{{ playbook_dir }}/extraconfigs/pod-security-admission-config.yaml"
      hosts:
        # # Optional hostvars that can be pased in to individual nodes include
        # # node_ip, node_name, bind_address, advertise_address, node_taints=[],
        # # node_labels=[], and node_external_ip
        192.168.56.101:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.101"
          # node_name: "server0.example.com"
          # bind_address: "10.10.10.10"
          # advertise_address: "10.10.10.10"
          # node_external_ip: "52.52.52.52"
          # node_taints:
          # - CriticalAddonsOnly=true:NoSchedule
          # cloud_provider_name: "aws"
        192.168.56.102:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.102"
        192.168.56.103:
          # node_labels:
          #   - server0Label=true
          node_ip: "192.168.56.103"
    rke2_agents:
      vars:
        rke2_config:
          # node-label:
          #   - agentGroupLabel=true
          
      # hosts:
      #   agent0.example.com:
      #     # node_labels:
      #     #   - agent0Label=true
      #     # node_ip: "10.10.10.10"
      #   agent1.example.com:
      #     # node_labels:
      #     #   - agent1Label=true
      #     # node_ip: "10.10.10.10"
```

**Comment by Falltrades** [comment]
Indeed, it is as you said, this PR is not needed.
Thanks for your guidance @GoldennDragonn !

**Pull request closed without merging**
