### PR TITLE
Support the generic cis profile

### LINKED ISSUE #171: CIS hardening does not support new generic cis profile
The `when` clause in [cis-hardening.yml](https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_common/tasks/cis-hardening.yml#L4) needs to support the new [generic cis profile](https://github.com/rancher/rke2/pull/4708)

### PR DESCRIPTION
**Pull request by laszlojau**
## What type of PR is this?

- [ ] bug
- [ ] cleanup
- [ ] documentation
- [x] feature

## What this PR does / why we need it:

Adds support for the generic `cis` profile 

## Which issue(s) this PR fixes:

Fixes #171

### CODE REVIEW

**Comment by jcox10** [comment]
@dgvigil can this be merged?

**Comment by dgvigil** [comment]
I'm sorry, but I am no longer a part of the company that maintains this repository. You will need to ping the other members.

**Comment by jcox10** [comment]
@aleiner this PR would be great to get merged in too if you have time

**Comment by aleiner** [comment]
I'll have someone take a look this week.

**Review by mddamato — APPROVED** [review]
lgtm

**Pull request merged**
