### PR TITLE
Add manifest feature #14

### PR DESCRIPTION
**Pull request by AYDEV-FR**
Hi,

I use your ansible script since a few weeks to deploy several clusters. Its evolution is at the top day by day!
Using rke2's functionality of adding manifest and having implemented it on my side.
I propose this PR to answer the issue #14.

What do you think about my implementation ?

Have a nice day !

### Proposed changes
Override and add manifest file feature.
RKE2 documented here :
- Override : https://docs.rke2.io/install/network_options/#canal-options
- Add Helm, or another yaml file : https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts

### Checklist

-   [X] I have read the [CONTRIBUTING](https://github.com/rancherfederal/rke2-ansible/blob/main/CONTRIBUTING.md) document
-> **FILE MISSING**

-   [X] I have added Molecule tests that prove my fix is effective or that my feature works
-> **No check molecule exists for the moment on the repositories**

-   [X] I have checked that all Molecule tests pass after adding my changes
-> **No check molecule exists for the moment on the repositories**

-   [X] I have updated any relevant documentation (`defaults/main/*.yml`, `README.md` and `CHANGELOG.md`)
-> **I have add some comments to describe how this features works**

### CODE REVIEW

**Comment by AYDEV-FR** [comment]
After too many test I could have this error, in case I don't use the feature, and the varaibale is unset.
I will fix it in my next commit in this PR/Branch

```
Fatal [...] FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'manifest_config_file_path' is undefined\n\nThe error appears to be in [...]/rke2-ansible/roles/rke2_common/tasks/add-manifest-addons.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Add manifest addons files\n  ^ here\n"}
```

**Comment by xom4ek** [comment]
When using this feature and bootstrap cluster with another cidr - rke2 didnt just didnt redeploy manifest for canal.

https://docs.rke2.io/install/network_options/#canal-options
```
The config needs to be copied over to the manifests directory before installing rke2:
```

But if swap "Start server" and "Add manifest" tasks - seems better for bootstrap.

**Comment by mddamato** [comment]
Thank you @xom4ek and @AYDEV-FR I believe this feature is working in MR #54 Please take a look at this and let me know if it works for you

**Comment by mddamato** [comment]
in #54

**Pull request closed without merging**
